Repository react-challengers/Codefolio, pull requests merged in 2023-02, with the labels that each got.

#15 Feat/ProfileImage Components
  Components/Common/ProfileImage.tsx
  public/images/anonProfile.jpeg
Labels: enhancement

#14 chore: ESLint - react/require-default-props 룰 수정
  .eslintrc.json
Labels: good first issue

#16 create components, add eslint rule, and edit reset.css
  .eslintrc.json
  Components/Common/DefaultButton.tsx
  Components/Layouts/GNB.tsx
  public/icons/notification.svg
  public/icons/person.svg
  public/icons/post.svg
  public/icons/search.svg
  styles/reset.css
  yarn.lock
Labels: enhancement

#23 feat(PositionTag): MyPage의 PositionTag 컴포넌트 구현
  Components/MyPage/PositionTag.tsx
Labels: enhancement

#24 feat(ProfileContainer): MyPage의 ProfileContainer 컴포넌트 구현
  Components/MyPage/ProfileContainer.tsx
Labels: enhancement

#26 Feat/tag
  Components/Common/Card/CardItem.tsx
  Components/Common/Card/IconWithCount.tsx
  Components/Common/Tags.tsx
  public/icons/ico-heart.svg
Labels: enhancement

#27 feat: 사이드바 컴포넌트 제작
  Components/Main/LargeCategory.tsx
  Components/Main/SideBar.tsx
  public/icons/bottom_arrow.svg
  public/icons/check.svg
Labels: enhancement

#29 feat (Toggle): Toggle 컴포넌트 구현
  Components/Common/Toggle.tsx
Labels: enhancement

#40 Feature/mypage 마이페이지 구현
  .eslintrc.json
  Components/Common/Toggle.tsx
  Components/MyPage/CardItemContainer.tsx
  Components/MyPage/EditProfileContainer.tsx
  Components/MyPage/MyPageContainer.tsx
  Components/MyPage/MypageTab.tsx
  Components/MyPage/PrivateProfileContainer.tsx
  Components/MyPage/ProfileContainer.tsx
  Components/MyPage/ShowProfileContainer.tsx
  Components/MyPage/Skill.tsx
  Components/MyPage/SkillList.tsx
  Components/MyPage/SwitchButton.tsx
  Components/MyPage/TabProfile.tsx
  Components/MyPage/TabProjectList.tsx
  Components/MyPage/UserInfoContainer.tsx
  hooks/common/useInput.ts
  pages/profile/[[...userId]].tsx
  pages/profile/detail/[id].tsx
  pages/profile/edit-profile/[id].tsx
  public/icons/cancel.svg
  public/icons/edit.svg
  public/icons/private.svg
  tsconfig.json
  types.d.ts
  utils/commons/getYearsArray.ts
Labels: enhancement

#43 Feature/DetailTitle
  Components/Detail/DetailTitle.tsx
  pages/detail/[id].tsx
Labels: enhancement

#45 Feat(DetailSide): 디테일 페이지 왼쪽 사이드 UI 구현
  Components/Common/ProjectInfoDropDown.tsx
  Components/Detail/DetailBox.tsx
  Components/Detail/DetailSide.tsx
  Components/Detail/DetailSideContainer.tsx
  Components/Detail/DetailWith.tsx
  pages/detail/[id].tsx
  public/icons/github.svg
Labels: enhancement

#42 feat(DetailHeader): 디테일 페이지 헤더 구현
  Components/Detail/DetailHeader.tsx
  Components/Detail/ShowMoreModal.tsx
  pages/detail/[id].tsx
  public/icons/bookmark.svg
  public/icons/like.svg
  public/icons/more.svg
Labels: enhancement

#48 Feat/related project
  .eslintrc.json
  Components/Detail/RelatedProject.tsx
  package.json
  public/icons/next_button.svg
  public/icons/prev_button.svg
Labels: enhancement

#34 Feat/main page 작성
  Components/Common/Card/CardItem.tsx
  Components/Common/Tags.tsx
  Components/Main/MainSection.tsx
  Components/Main/SideBar.tsx
  lib/recoil/atoms.ts
  lib/recoil/index.ts
  pages/_app.tsx
  pages/index.tsx
  public/images/anonImage.png
Labels: enhancement

#52 Feat/detail
  Components/Common/Card/CardItem.tsx
  Components/Common/Tags.tsx
  Components/Detail/Comment.tsx
  Components/Detail/DetailModal.tsx
  Components/Detail/RelatedProject.tsx
  Components/Detail/index.ts
  Components/Main/MainSection.tsx
  pages/detail/[id].tsx
  pages/index.tsx
  styles/reset.css
Labels: enhancement

#54 Feat/detail comment
  Components/Detail/CommentInput.tsx
  Components/Detail/CommentItem.tsx
  Components/Detail/CommentList.tsx
  hooks/common/useInput.ts
  package.json
  pages/_app.tsx
  pages/detail/[id].tsx
  yarn.lock
Labels: enhancement

#55 Feat/post page
  .eslintrc.json
  Components/Common/DropDown.tsx
  Components/Common/Skill/Skill.tsx
  Components/Common/Skill/SkillList.tsx
  Components/MyPage/EditProfileContainer.tsx
  Components/Post/FieldDropDown.tsx
  Components/Post/Post.tsx
  Components/Post/PostEditor.tsx
  Components/Post/PostTitle.tsx
  Components/Post/ProjectInfo.tsx
  Components/Post/ProjectInfoDropDown.tsx
  Components/Post/WithPeople.tsx
  lib/recoil/index.ts
  lib/recoil/postAtoms.ts
  package.json
  pages/create-post.tsx
  public/icons/close.png
  public/icons/color_fill.svg
  types.d.ts
  utils/commons/getYYYYMM.ts
  yarn.lock
Labels: enhancement

#58 Feat/post page
  Components/Common/Skill/Skill.tsx
  Components/Detail/CommentInput.tsx
  Components/Detail/DetailWith.tsx
  Components/Detail/ShowMoreModal.tsx
  Components/Post/FieldDropDown.tsx
  Components/Post/Post.tsx
  Components/Post/ProjectInfoDropDown.tsx
  pages/detail/[id].tsx
  yarn.lock
Labels: enhancement

#78 refactor(PostTitle, SideBar): border 삭제와 key값 추가
  Components/Main/SideBar.tsx
  Components/Post/PostTitle.tsx
Labels: bug

#84 fix(TabProfile): 전화번호 숫자 전용 및 유효성 검사
  Components/Common/index.ts
  Components/MyPage/EditProfileContainer.tsx
  Components/MyPage/index.ts
  lib/recoil/index.ts
  lib/recoil/myPageAtoms.ts
  pages/profile/[[...userId]].tsx
  types.d.ts
Labels: bug

#85 Fix/card items
  Components/Common/Card/CardItem.tsx
  Components/Detail/RelatedProject.tsx
  Components/Main/MainSection.tsx
  Components/MyPage/CardItemContainer.tsx
  Components/MyPage/TabProjectList.tsx
  next.config.js
  package.json
  pages/_app.tsx
  pages/profile/[[...userId]].tsx
  types.d.ts
  utils/APIs/supabase/getAllPosts.ts
  utils/APIs/supabase/index.ts
  utils/card/findThumbnailInContent.ts
  utils/card/getPostDate.ts
  utils/card/index.ts
Labels: enhancement

#86 Feat/drop down
  Components/Common/DropDown.tsx
  Components/MyPage/EditProfileContainer.tsx
  pages/profile/[[...userId]].tsx
Labels: bug

#87 hotfix: vercel에서 배포시 발생하는 오류를 수정합니다.
  Components/Common/ProjectInfoDropDown.tsx
Labels: bug

#88 feat(UserInfoContainer): 로그아웃 기능
  Components/MyPage/UserInfoContainer.tsx
Labels: enhancement

#93 Feat/check user gnb
  Components/Layouts/GNB.tsx
  Components/MyPage/UserInfoContainer.tsx
  lib/recoil/index.ts
  lib/recoil/userLoginCheck.ts
  pages/_app.tsx
Labels: enhancement

#117 fix: useEffect dependency Array : warring
  Components/Detail/DetailHeader.tsx
  Components/Layouts/GNB.tsx
  Components/MyPage/UserInfoContainer.tsx
  Components/Post/PostEditor.tsx
  pages/auth/login.tsx
  pages/auth/signup.tsx
  pages/profile/[[...userId]].tsx
Labels: bug

#119 fix: 배포버전의 스와이퍼 버튼이 동작하지 않는 문제 해결
  Components/Detail/RelatedProject.tsx
  Components/Detail/SwiperNextButton.tsx
  Components/Detail/SwiperPrevButton.tsx
Labels: bug

#122 fix: 배포시 폰트가 적용되지 않던 문제를 해결합니다.
  pages/_document.tsx
  styles/global.css
Labels: bug

#120 fix(GNB): 로그인 시 버튼 변경 문제
  pages/auth/login.tsx
  pages/auth/signup.tsx
Labels: bug

#121 댓글 auth와 연동 했습니다.
  Components/Detail/Comment.tsx
  Components/Detail/CommentInput.tsx
  Components/Detail/CommentItem.tsx
  Components/Detail/CommentList.tsx
  utils/commons/authValidate.ts
  utils/commons/viewCreateAt.ts
Labels: enhancement

#123 feat(UserInfoContainer): 마이페이지 유져 백그라운드 기능 추가
  Components/MyPage/Banner.tsx
  Components/MyPage/UserInfoContainer.tsx
  lib/recoil/index.ts
  lib/recoil/myPageAtoms.ts
  pages/profile/[[...userId]].tsx
  types.d.ts
Labels: enhancement

#125 Feat/DetailHeader
  Components/Detail/DetailContent.tsx
  Components/Detail/DetailHeader.tsx
  Components/Detail/DetailSide.tsx
  Components/Detail/DetailTitle.tsx
  Components/Detail/DetailWith.tsx
  Components/Detail/ShowMoreModal.tsx
  pages/detail/[id].tsx
  public/icons/bookmarkHover.svg
  public/icons/likeHover.svg
Labels: enhancement

#129 feat: main page 카테고리별 필터 기능 추가
  Components/Main/MainSection.tsx
  Components/Main/SideBar.tsx
Labels: enhancement

#128 Feat/input box style
  Components/MyPage/UserInfoContainer.tsx
  lib/recoil/index.ts
  lib/recoil/myPageAtoms.ts
Labels: enhancement

#132 Fix/thumbnail error
  Components/Common/Card/CardItem.tsx
  Components/Detail/Comment.tsx
  Components/Detail/CommentInput.tsx
Labels: bug

#139 feat: post 시 user_id 포함하도록 추가
  Components/Post/Post.tsx
Labels: bug

#147 fix: #141 이슈를 해결
  Components/Common/Card/CardItem.tsx
Labels: bug

#146 fix: 카테고리 선택 에러 해결
  Components/Main/LargeCategory.tsx
Labels: bug

#142 feat: 게시글 좋아요, 댓글 및 최신순 정렬
  Components/Common/Card/CardItem.tsx
  Components/Detail/CommentInput.tsx
  Components/Detail/CommentItem.tsx
  Components/Detail/DetailHeader.tsx
  Components/Detail/RelatedProject.tsx
  Components/Main/MainSection.tsx
  Components/MyPage/CardItemContainer.tsx
  public/icons/comment.svg
  public/icons/메인/mdi_comment-outline.svg
  types.d.ts
  utils/APIs/supabase/getAllPosts.ts
Labels: enhancement

#152 fix: 로그인 로그아웃 버튼 스타일 변경
  Components/Layouts/GNB.tsx
  Components/MyPage/UserInfoContainer.tsx
  public/icons/logout.svg
Labels: style

#155 Fix/error 1.0.0 #133
  Components/Common/Card/CardItem.tsx
  Components/Common/DropDown.tsx
  Components/Common/Modal.tsx
  Components/Common/Skill/Skill.tsx
  Components/Common/Skill/SkillList.tsx
  Components/Common/Tags.tsx
  Components/Detail/Comment.tsx
  Components/Detail/CommentInput.tsx
  Components/Detail/DetailHeader.tsx
  Components/Detail/DetailSide.tsx
  Components/Detail/RelatedProject.tsx
  Components/Detail/ShowMoreModal.tsx
  Components/Layouts/Footer.tsx
  Components/Main/MainSection.tsx
  Components/MyPage/EditProfileContainer.tsx
  Components/MyPage/MypageTab.tsx
  Components/MyPage/ShowProfileContainer.tsx
  Components/MyPage/UserInfoContainer.tsx
  Components/Post/Post.tsx
  Components/Post/ProjectInfo.tsx
  Components/Post/ProjectInfoDropDown.tsx
  Components/Post/WithPeople.tsx
  hooks/query/useUserProfile.ts
  lib/recoil/postAtoms.ts
  next.config.js
  pages/_app.tsx
  pages/auth/signup.tsx
  pages/create-post.tsx
  pages/detail/[id].tsx
  pages/edit-post/[id].tsx
  pages/profile/[[...userId]].tsx
  styles/reset.css
  types.d.ts
  types/supabase.ts
  utils/APIs/supabase/getUser.ts
  utils/APIs/supabase/getUserProfile.ts
  utils/APIs/supabase/patchUserProfile.ts
  utils/commons/authUtils.ts
Labels: bug, enhancement

#159 Doc/readme.md 1.0.0
  README.md
  package.json
Labels: documentation

#160 Update README.md
  README.md
  package.json
Labels: documentation

#176 fix: 타이틀을 변경합니다.
  pages/_app.tsx
  pages/index.tsx
Labels: bug

#178 fix(ProjectInfoDropDown): 개발 스택 제목 width 고정
  Components/Post/ProjectInfoDropDown.tsx
Labels: style

#179 Fix/tagUI
  Components/Post/ProjectInfoDropDown.tsx
  Components/Post/WithPeople.tsx
Labels: style

#183 Feat/tag enter event, Fix/tag vailidation
  Components/Common/Skill/Skill.tsx
  Components/Common/Skill/SkillList.tsx
Labels: bug, enhancement

#181 fix: 프로젝트 기간, 시작월 유효성 검사 추가해야함 #166
  Components/Post/ProjectInfoDropDown.tsx
Labels: bug

#184 fix: 게시글 진입 시 북마크,좋아요 체크
  Components/Detail/DetailHeader.tsx
Labels: bug

#180 댓글에 보여지는 유저프로필 및 유저이름 수정
  Components/Detail/Comment.tsx
  Components/Detail/CommentInput.tsx
  Components/Detail/CommentItem.tsx
  Components/Detail/CommentList.tsx
Labels: bug

#185 fix: detail title 폰트 컬러 accent-color 적용해보기 #174
  Components/Detail/DetailTitle.tsx
Labels: style

#186 Feat/ResetMain
  Components/Layouts/GNB.tsx
  Components/Main/SideBar.tsx
Labels: enhancement

#188 fix: tag overflow fix
  Components/Common/Tags.tsx
Labels: bug

#187 Fix/Editor
  Components/Detail/DetailContent.tsx
  Components/Post/PostEditor.tsx
  package.json
Labels: enhancement

#189 Feat/profile phone number and year
  Components/Common/DropDown.tsx
  Components/MyPage/EditProfileContainer.tsx
  Components/MyPage/ShowProfileContainer.tsx
  Components/MyPage/SwitchButton.tsx
  Components/MyPage/TabProfile.tsx
  Components/MyPage/UserInfoContainer.tsx
  hooks/query/useUserProfile.ts
  lib/recoil/index.ts
  lib/recoil/myPageAtoms.ts
Labels: enhancement

#192 Hotfix/#191
  Components/Detail/CommentInput.tsx
  Components/MyPage/EditProfileContainer.tsx
  Components/MyPage/SwitchButton.tsx
  hooks/query/useUserProfile.ts
Labels: bug, enhancement

#193 Chore/folder refactoring
  Components/Common/Auth/index.ts
  Components/Common/LongButton.tsx
  Components/Common/index.ts
  Components/CreatePost/Post/FieldDropDown.tsx
  Components/CreatePost/Post/Post.tsx
  Components/CreatePost/Post/PostTitle.tsx
  Components/CreatePost/Post/ProjectInfo.tsx
  Components/CreatePost/Post/ProjectInfoDropDown.tsx
  Components/CreatePost/Post/WithPeople.tsx
  Components/CreatePost/PostEditor.tsx
  Components/Detail/Comment/Comment.tsx
  Components/Detail/Comment/CommentInput.tsx
  Components/Detail/Comment/CommentItem.tsx
  Components/Detail/Comment/CommentList.tsx
  Components/Detail/DetailContent.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
  Components/Detail/DetailHeader/ShowMoreModal.tsx
  Components/Detail/DetailSide/DetailBox.tsx
  Components/Detail/DetailSide/DetailSide.tsx
  Components/Detail/DetailSide/DetailSideContainer.tsx
  Components/Detail/DetailSide/DetailWith.tsx
  Components/Detail/RelatedProject/RelatedProject.tsx
  Components/Detail/RelatedProject/SwiperNextButton.tsx
  Components/Detail/RelatedProject/SwiperPrevButton.tsx
  Components/Detail/index.ts
  Components/Layouts/index.ts
  Components/Main/DetailModal.tsx
  Components/Main/MainSection.tsx
  Components/Main/SideBar/LargeCategory.tsx
  Components/Main/SideBar/SideBar.tsx
  Components/Main/index.ts
  Components/MyPage/CardItemContainer.tsx
  Components/MyPage/TabProfile/DropDown.tsx
  Components/MyPage/TabProfile/EditProfileContainer.tsx
  Components/MyPage/TabProfile/PositionTag.tsx
  Components/MyPage/TabProfile/PrivateProfileContainer.tsx
  Components/MyPage/TabProfile/ProfileContainer.tsx
  Components/MyPage/TabProfile/ShowProfileContainer.tsx
  Components/MyPage/TabProfile/SwitchButton.tsx
  Components/MyPage/TabProfile/TabProfile.tsx
  Components/MyPage/UserInfoContainer/Banner.tsx
  Components/MyPage/UserInfoContainer/UserInfoContainer.tsx
  Components/MyPage/index.ts
  Components/index.ts
  pages/404.tsx
  pages/500.tsx
  pages/_app.tsx
  pages/auth/login.tsx
  pages/auth/signup.tsx
  pages/create-post.tsx
  pages/detail/[id].tsx
  pages/edit-post/[id].tsx
  pages/index.tsx
Labels: refactor

#195 Readme 업데이트
  README.md
Labels: documentation

#206 chore: theme provider 설정
  styles/styled.d.ts
  styles/theme.ts
Labels: enhancement

#231 fix: sidebar 랜더링시 위치이동 현상 제거
  styles/global.css
Labels: bug

#229 fix(MainSection) 메인페이지 최신,추천,댓글 드롭다운 z-index 2로 변경
  Components/Main/MainSection.tsx
Labels: bug

#228 fix(useStopScroll) 모달 open시 백드롭에서 스크롤 방지
  Components/Main/DetailModal.tsx
  hooks/common/index.ts
  hooks/common/useStopScroll.ts
Labels: bug

#226 fix: 좋아요 코멘트 인터렉션 시 카운트 업데이트
  Components/Detail/Comment/CommentInput.tsx
  Components/Detail/Comment/CommentItem.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
Labels: bug

#227 fix(UserInfo)최초 로그인시 유저 정보 없음 디버깅
  Components/MyPage/UserInfoContainer/UserInfoContainer.tsx
  hooks/query/useUserProfile.ts
Labels: bug

#230 refact: 카테고리 수정
  Components/CreatePost/Post/FieldDropDown.tsx
  Components/CreatePost/Post/Post.tsx
  Components/CreatePost/Post/ProjectInfoDropDown.tsx
  Components/Detail/DetailTitle.tsx
  Components/Main/MainSection.tsx
  Components/Main/SideBar/SideBar.tsx
Labels: refactor

#232 fix: global css 적용 위치 변경
  Components/Main/SideBar/SideBar.tsx
  styles/global.css
  styles/reset.css
Labels: bug

#234 Feat/text-editor-change
  Components/CreatePost/Post/Post.tsx
  Components/CreatePost/PostEditor.tsx
  Components/Detail/DetailArticle.tsx
  Components/Detail/DetailContent.tsx
  Components/MyPage/UserInfoContainer/UserInfoContainer.tsx
  lib/recoil/index.ts
  lib/recoil/postAtoms.ts
  next.config.js
  package.json
  pages/create-post.tsx
  pages/edit-post/[id].tsx
Labels: refactor

#235 Feat/profile background image
  Components/CreatePost/PostEditor.tsx
  Components/MyPage/UserInfoContainer/Banner.tsx
  Components/MyPage/UserInfoContainer/UserInfoContainer.tsx
  Components/MyPage/UserInfoContainer/useUserImage.ts
  hooks/query/useUserProfile.ts
  lib/recoil/index.ts
  lib/recoil/myPageAtoms.ts
  types.d.ts
  utils/commons/uploadImage.ts
Labels: enhancement

#237 Feat/amplitude
  package.json
  pages/_app.tsx
  pages/index.tsx
  utils/amplitude/amplitude.ts
Labels: documentation
