Repository react-challengers/Codefolio, pull requests merged in 2023-03, with the labels that each got.

#245 hotfix(PostEditor): any 타입 수정
  Components/CreatePost/PostEditor.tsx
  styles/theme.ts
Labels: refactor

#247 fix: 썸네일 오류 해결
  utils/card/findThumbnailInContent.ts
Labels: bug

#249 Feat/main page style
  Components/Common/Card/CardItem.tsx
  Components/Common/Card/IconWithCount.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
  Components/Detail/RelatedProject/RelatedProject.tsx
  Components/Main/CategoryTag.tsx
  Components/Main/HomeDropDownIcon.tsx
  Components/Main/MainSection.tsx
  Components/Main/SideBar/SideBar.tsx
  Components/MyPage/CardItemContainer.tsx
  hooks/query/index.ts
  hooks/query/useCheckInteraction.ts
  public/icons/bookmark.svg
  public/icons/bookmarkHover.svg
  public/icons/check.svg
  public/icons/close.svg
  public/icons/comment.svg
  public/icons/commentHover.svg
  public/icons/likeHover.svg
  styles/global.css
  types.d.ts
  utils/APIs/supabase/getIsComment.ts
  utils/APIs/supabase/index.ts
Labels: enhancement, style

#248 Fix/PostEditor-input-image
  Components/Common/Modal.tsx
  Components/CreatePost/PostEditor.tsx
  utils/commons/compressImg.ts
  utils/commons/uploadImage.ts
  utils/commons/validationImage.ts
Labels: bug, enhancement, style, refactor

#251 feat: loading skeleton 적용
  Components/Main/MainSection.tsx
  package.json
  yarn.lock
Labels: enhancement

#252 Style/auth page ( 디자인 + 유효성 검사)
  Components/Common/Auth/AuthButton.tsx
  Components/Common/Auth/AuthInput.tsx
  Components/Common/Auth/ErrorMassageBox.tsx
  Components/Common/Auth/HelperTextBox.tsx
  Components/Common/Auth/ValidateText.tsx
  Components/Common/Auth/index.ts
  Components/Layouts/Footer.tsx
  pages/auth/login.tsx
  pages/auth/signup.tsx
  public/icons/ico_ExclamationMark.svg
  public/icons/ico_close_16.svg
  public/icons/ico_github.svg
  public/icons/ico_google.svg
  public/images/login_background.png
  public/images/signup_background.png
  utils/commons/authUtils.ts
Labels: style, refactor

#253 Feat/etc styles
  Components/Common/DropDown.tsx
  Components/Common/LongButton.tsx
  Components/Common/ProfileImage.tsx
  Components/Common/index.ts
  Components/Detail/Comment/CommentInput.tsx
  Components/Detail/Comment/CommentItem.tsx
  Components/Detail/DetailArticle.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
  Components/Layouts/GNB.tsx
  Components/Layouts/Notification.tsx
  Components/Layouts/NotificationBookmarkIcon.tsx
  Components/Layouts/NotificationCommentIcon.tsx
  Components/Layouts/NotificationItem.tsx
  Components/Layouts/NotificationLikeIcon.tsx
  Components/Layouts/SearchBar.tsx
  Components/Main/MainSection.tsx
  lib/recoil/index.ts
  lib/recoil/notificationAtoms.ts
  lib/recoil/searchValue.ts
  pages/404.tsx
  pages/500.tsx
  pages/_app.tsx
  pages/search.tsx
  public/icons/search.svg
  public/images/error_boy.png
  types.d.ts
  utils/APIs/supabase/getNotification.ts
  utils/APIs/supabase/getSingleUser.ts
  utils/APIs/supabase/index.ts
  utils/APIs/supabase/postNotificationRead.ts
  utils/notification/createNotificationContent.ts
Labels: enhancement, style

#255 fix: 디자이너 컨펌에 대한 feedback
  Components/Common/Auth/AuthButton.tsx
  Components/Common/Auth/ErrorMessageBox.tsx
  Components/Common/Auth/HelperTextBox.tsx
  Components/Common/Auth/index.ts
  pages/auth/login.tsx
  pages/auth/signup.tsx
Labels: hotfix

#256 style: GNB 아이콘 적용
  Components/Layouts/CreatePostIcon.tsx
  Components/Layouts/GNB.tsx
  Components/Layouts/NotificationIcons.tsx
Labels: enhancement

#250 Feat/DetailPage
  Components/Common/ConfirmModal.tsx
  Components/Common/DefaultButton.tsx
  Components/Common/Tags.tsx
  Components/CreatePost/Post/ProjectInfoDropDown.tsx
  Components/Detail/Comment/CommentInput.tsx
  Components/Detail/Comment/CommentItem.tsx
  Components/Detail/Comment/CommentList.tsx
  Components/Detail/DetailArticle.tsx
  Components/Detail/DetailBadges.tsx
  Components/Detail/DetailBadgesContainer.tsx
  Components/Detail/DetailContent.tsx
  Components/Detail/DetailHeader/DeleteModal.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
  Components/Detail/DetailHeader/ShowMoreModal.tsx
  Components/Detail/DetailSide/DetailBadgeModal.tsx
  Components/Detail/DetailSide/DetailSide.tsx
  Components/Detail/DetailSide/DetailSideBadges.tsx
  Components/Detail/DetailSide/DetailSideContainer.tsx
  Components/Detail/DetailSide/DetailSidePeople.tsx
  Components/Detail/DetailSide/DetailSideProject.tsx
  Components/Detail/DetailSide/DetailWith.tsx
  Components/Detail/DetailTitle.tsx
  Components/Detail/RelatedProject/RelatedProject.tsx
  pages/profile/[[...userId]].tsx
  public/icons/badge-check.svg
  public/icons/badge-code.svg
  public/icons/badge-light.svg
  public/icons/badge-setting.svg
  public/icons/github.svg
  public/icons/more-on.svg
  types.d.ts
  utils/APIs/supabase/addPostBadge.ts
  utils/APIs/supabase/deletePostBadge.ts
  utils/APIs/supabase/getBadgeByUid.ts
  utils/APIs/supabase/getPostBadges.ts
  utils/detail/getTextColorByBackgroundColor.ts
Labels: style

#257 Feat/my page1.1.0 style
  Components/Common/Input.tsx
  Components/Common/index.ts
  Components/Detail/Comment/CommentItem.tsx
  Components/Detail/Comment/CommentList.tsx
  Components/Detail/DetailArticle.tsx
  Components/MyPage/MypageTab.tsx
  Components/MyPage/TabProfile/BadgeIcon.tsx
  Components/MyPage/TabProfile/DropDown.tsx
  Components/MyPage/TabProfile/EditProfileContainer.tsx
  Components/MyPage/TabProfile/GoodJobBadge.tsx
  Components/MyPage/TabProfile/ProfileContainer.tsx
  Components/MyPage/TabProfile/ShowProfileContainer.tsx
  Components/MyPage/TabProfile/SwitchButton.tsx
  Components/MyPage/UserInfoContainer/Banner.tsx
  Components/MyPage/UserInfoContainer/UserInfoContainer.tsx
  Components/MyPage/index.ts
  hooks/query/useUserProfile.ts
  lib/recoil/index.ts
  lib/recoil/myPageAtoms.ts
  pages/profile/[[...userId]].tsx
  public/icons/36-communication.svg
  public/icons/36-implementation.svg
  public/icons/36-initiative.svg
  public/icons/36-pencil.svg
  public/icons/36-puzzle.svg
  public/icons/ico-edit.svg
  public/icons/ico-photo.svg
  styles/styled.d.ts
  styles/theme.ts
  types.d.ts
  utils/APIs/supabase/getAllPosts.ts
  utils/APIs/supabase/getNotification.ts
  utils/APIs/supabase/getOnePost.ts
  utils/APIs/supabase/getUserProfile.ts
  utils/commons/checkIsPhoneNumber.ts
Labels: enhancement, style, refactor

#259 Fix/refactor style
  Components/Layouts/Footer.tsx
  Components/Layouts/GNB.tsx
  pages/_document.tsx
  public/images/anonImage.png
  public/images/anonImage.webp
  public/images/ogImage.png
  public/logos/favicon.png
  public/logos/mainLogo.svg
  utils/card/findThumbnailInContent.ts
Labels: enhancement, style

#258 Style/post-page 디자인에 맞춘 변경
  Components/Common/Card/CardItem.tsx
  Components/Common/HelperTextBox.tsx
  Components/Common/Skill/Skill.tsx
  Components/Common/Skill/SkillList.tsx
  Components/Common/index.ts
  Components/CreatePost/Post/FieldDropDown.tsx
  Components/CreatePost/Post/Post.tsx
  Components/CreatePost/Post/PostErrorMessage.tsx
  Components/CreatePost/Post/PostTitle.tsx
  Components/CreatePost/Post/ProjectInfo.tsx
  Components/CreatePost/Post/ProjectInfoDropDown.tsx
  Components/CreatePost/Post/WithPeople.tsx
  Components/CreatePost/PostEditor.tsx
  Components/Detail/DetailArticle.tsx
  lib/recoil/index.ts
  lib/recoil/myPageAtoms.ts
  lib/recoil/postAtoms.ts
  lib/recoil/postValidateAtoms.ts
  pages/create-post.tsx
  pages/edit-post/[id].tsx
  public/icons/arrow_down.svg
  public/icons/disable_check.svg
  public/icons/enable_check.svg
  public/icons/trash_can.svg
  public/images/arrow_down.jpg
  types.d.ts
  utils/commons/checkUrl.ts
Labels: enhancement, style

#278 fix(EditProfile): 휴대전화 input type number -> tel
  Components/MyPage/TabProfile/EditProfileContainer.tsx
Labels: hotfix

#280 Fix/profile tab activate edit
  Components/Common/Input.tsx
  Components/MyPage/TabProfile/EditProfileContainer.tsx
  Components/MyPage/UserInfoContainer/UserInfoContainer.tsx
  hooks/common/index.ts
  hooks/common/useScrollTop.ts
Labels: hotfix

#281 fix(Detail/SideBadge, BadgeModal): 모달 위치 변경
  Components/Detail/DetailSide/DetailBadgeModal.tsx
  Components/Detail/DetailSide/DetailSideBadges.tsx
Labels: hotfix

#282 fix(DetailTitle): Container에 space-between 정상 적용
  Components/Detail/DetailTitle.tsx
Labels: hotfix

#283 fix: main page min height 추가
  Components/Main/MainSection.tsx
Labels: style

#284 feat: 알람 시간 추가
  Components/Layouts/NotificationItem.tsx
  utils/commons/viewCreateAt.ts
Labels: enhancement, hotfix

#285 fix: 검색시 value가 안들어오던 문제 해결
  Components/Layouts/SearchBar.tsx
Labels: bug, hotfix

#292 fix: Loader 변경
  Components/Detail/DetailArticle.tsx
  Components/Layouts/Notification.tsx
  Components/MyPage/UserInfoContainer/UserInfoContainer.tsx
  pages/search.tsx
Labels: style

#291 fix: 최초 진입 시 본인 프로필 가져오기
  Components/CreatePost/Post/WithPeople.tsx
  hooks/query/useUserProfile.ts
Labels: bug, hotfix

#290 fix: 이미지 업로드시 모달 스타일 수정
  Components/CreatePost/ImageUploadText.tsx
  Components/CreatePost/PostEditor.tsx
  public/icons/image-upload-text.svg
Labels: style, hotfix

#294 feat: enter key 핸들링
  pages/auth/login.tsx
Labels: enhancement

#293 feat(Footer): Footer 스타일 반영
  Components/Layouts/Footer.tsx
  pages/search.tsx
Labels: style

#286 Fix/Image-file-name
  Components/CreatePost/Post/Post.tsx
  Components/CreatePost/Post/PostTitle.tsx
  Components/CreatePost/PostEditor.tsx
  Components/Detail/RelatedProject/RelatedProject.tsx
  Components/Main/MainSection.tsx
  Components/MyPage/CardItemContainer.tsx
  lib/recoil/index.ts
  lib/recoil/postAtoms.ts
  pages/edit-post/[id].tsx
  pages/search.tsx
  types.d.ts
  utils/card/findThumbnailInContent.ts
Labels: hotfix

#295 feat: post 함께한 사람들 유효성 검사 추가
  Components/Common/Auth/AuthInput.tsx
  Components/Common/Auth/ErrorMessageBox.tsx
  Components/Common/Auth/HelperTextBox.tsx
  Components/Common/HelperTextBox.tsx
  Components/Common/Skill/SkillList.tsx
  Components/CreatePost/Post/Post.tsx
  Components/CreatePost/Post/PostErrorMessage.tsx
  Components/CreatePost/Post/ProjectInfoDropDown.tsx
  Components/CreatePost/Post/WithPeople.tsx
  Components/Detail/Comment/CommentInput.tsx
  Components/MyPage/TabProfile/EditProfileContainer.tsx
  lib/recoil/index.ts
  lib/recoil/postValidateAtoms.ts
  pages/auth/login.tsx
  pages/auth/signup.tsx
Labels: enhancement

#302 hotfix!
  Components/CreatePost/Post/WithPeople.tsx
  Components/CreatePost/PostEditor.tsx
  lib/recoil/postAtoms.ts
Labels: hotfix

#303 hotfix: 드롭다운 아이템변경, 전역 테마 dark mode 적용, 불릿포인트 적용
  Components/CreatePost/Post/FieldDropDown.tsx
  Components/CreatePost/PostEditor.tsx
  Components/Detail/DetailContent.tsx
  pages/_app.tsx
Labels: hotfix

#315 fix(Post): 수정 후 postId가 바뀌는 현상
  Components/CreatePost/Post/Post.tsx
Labels: bug

#316 fix(WithPeople): 함께한 사람들 포지션 버그 수정
  Components/CreatePost/Post/FieldPicker.tsx
  Components/CreatePost/Post/WithPeople.tsx
Labels: bug

#317 Fix/error 깃허브 링크 error
  Components/CreatePost/Post/Post.tsx
  Components/Detail/DetailSide/DetailSide.tsx
  Components/Detail/DetailSide/DetailSideBadges.tsx
  Components/Detail/DetailSide/DetailSidePeople.tsx
  Components/Detail/DetailSide/DetailWith.tsx
Labels: hotfix

#324 feat: 드롭다운 및 모달 외부 화면 클릭 시 드롭다운 및 모달이 종료되는 기능 구현
  Components/Common/ConfirmModal.tsx
  Components/CreatePost/Post/FieldPicker.tsx
  Components/CreatePost/Post/ProjectInfoDropDown.tsx
  Components/Detail/Comment/CommentItem.tsx
  Components/Detail/DetailArticle.tsx
  Components/Detail/DetailHeader/ShowMoreModal.tsx
  Components/Detail/DetailSide/DetailBadgeModal.tsx
  hooks/query/useOutsideClick.ts
Labels: enhancement

#325 Feat/throttle debounce
  Components/Detail/DetailBadges.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
  Components/MyPage/TabProfile/GoodJobBadge.tsx
Labels: enhancement, refactor

#326 fix(storage): 이미지 업로드시 파일 압축 전체 적용
  Components/Common/ProfileImage.tsx
  Components/CreatePost/Post/PostTitle.tsx
  Components/MyPage/UserInfoContainer/Banner.tsx
  Components/MyPage/UserInfoContainer/useUserImage.ts
Labels: refactor

#332 fix: 데이트 피커 스타일 변경
  Components/CreatePost/Post/ProjectInfoDropDown.tsx
Labels: style

#333 style(MainSection): 메인 섹션의 레이아웃을 수정합니다.
  Components/Main/MainSection.tsx
Labels: style

#334 style: 삭제 모달 컬러 변경
  Components/Common/ConfirmModal.tsx
  Components/Detail/DetailHeader/ShowMoreModal.tsx
Labels: style

#337 Feat/infinite scroll (두배 이벤트 수정해야합니다)
  Components/Main/MainSection.tsx
  lib/recoil/InfiniteScroll.ts
  utils/APIs/supabase/getAllPostsCount.ts
  utils/APIs/supabase/getInfinitePosts.ts
Labels: bug

#338 fix: main page justify-content 수정
  Components/Main/MainSection.tsx
Labels: bug, hotfix

#339 fix: 이미지 뒤로 텍스트가 넘어가는 현상 픽스
  Components/Detail/DetailTitle.tsx
Labels: bug, hotfix

#343 fix: 삭제가 안되는 버그를 고칩니다
  Components/Common/ConfirmModal.tsx
  Components/Detail/DetailHeader/ShowMoreModal.tsx
  Components/Main/MainSection.tsx
Labels: hotfix

#344 hotfix 1.2.0
  Components/Common/ConfirmModal.tsx
  Components/Detail/DetailHeader/ShowMoreModal.tsx
  Components/Main/MainSection.tsx
Labels: hotfix

#345 hotfix: 프로필 댓글 placeholder에 이름 수정
  Components/MyPage/TabProfile/ProfileCommentInput.tsx
Labels: hotfix

#351 fix(DropDown, EditProfile, MyPageAtoms): 출생년도
  Components/MyPage/TabProfile/DropDown.tsx
  Components/MyPage/TabProfile/EditProfileContainer.tsx
  Components/MyPage/TabProfile/ShowProfileContainer.tsx
  hooks/query/useUserProfile.ts
  lib/recoil/myPageAtoms.ts
  types.d.ts
Labels: bug

#355 fix(Profile, useUserProfile, GNB): MyPage Post 갱신
  Components/Layouts/GNB.tsx
  hooks/query/useUserProfile.ts
  pages/profile/[[...userId]].tsx
Labels: bug

#362 fix(GNB): 알림 드랍다운 겹치는 문제 Z-index로 해결
  Components/Common/PrimaryButton.tsx
  Components/Detail/DetailTitle.tsx
  Components/Layouts/GNB.tsx
Labels: bug

#363 fix: detail에서 깃,배포 링크 안보이는 에러
  Components/Detail/DetailArticle.tsx
  Components/Detail/DetailSide/DetailSide.tsx
  Components/Detail/DetailSide/DetailSideProject.tsx
Labels: bug

#357 Feat/infinite scroll 2배 이벤트를 종료하겠습니다
  Components/Main/MainSection.tsx
  hooks/common/useIntersect.ts
  pages/_app.tsx
Labels: bug

#359 feat: 디테일 페이지 뒤로가기 버튼 구현
  Components/Detail/DetailHeader/DetailHeader.tsx
  public/icons/back-arrow.svg
Labels: enhancement

#354 fix: 디테일 페이지 스크롤바 적용
  Components/Main/DetailModal.tsx
Labels: hotfix

#349 fix: 깃허브 주소 유효성 검사
  Components/CreatePost/Post/Post.tsx
  utils/commons/checkUrl.ts
Labels: hotfix

#365 fix: 이벤트 전파 버블링 막기
  Components/Main/DetailModal.tsx
Labels: hotfix

#381 디자인 요청사항 반영
  Components/Detail/DetailBadgesContainer.tsx
  Components/Detail/RelatedProject/RelatedProject.tsx
  Components/Layouts/SearchBar.tsx
  public/images/anonImage.png
  public/images/anonImage.webp
  public/images/thumnail_default.webp
  utils/card/findThumbnailInContent.ts
Labels: style

#383 feat: topButton 기능 구현
  Components/Common/TopButton.tsx
  Components/Main/DetailModal.tsx
  Components/Main/MainSection.tsx
  pages/index.tsx
  public/icons/top-button.svg
Labels: enhancement

#382 style(PrimaryButton): 컬러, 폰트사이즈, 커서 업데이트
  Components/Common/PrimaryButton.tsx
Labels: style

#375 Feat/Modile-response
  Components/Common/Auth/AuthButton.tsx
  Components/Common/Auth/AuthInput.tsx
  Components/Common/Auth/ErrorMessageBox.tsx
  Components/Common/Auth/HelperTextBox.tsx
  Components/Layouts/Footer.tsx
  Components/Layouts/GNB.tsx
  Components/Layouts/Notification.tsx
  Components/Layouts/SearchBar.tsx
  Components/Main/MainSection.tsx
  Components/Mobile/HambergerMenu.tsx
  Components/Mobile/SelectField.tsx
  hooks/common/useIsMobile.ts
  package.json
  pages/auth/login.tsx
  pages/auth/signup.tsx
  pages/index.tsx
  pages/m-preparing.tsx
  public/icons/Mobile/hamberger_menu.svg
Labels: enhancement

#380 Feat/landing page
  Components/Main/Banner.tsx
  Components/Main/index.ts
  pages/index.tsx
  pages/on-boarding.tsx
  public/images/main-banner.png
  public/images/on-boarding-01.png
  public/images/on-boarding-02.png
  public/images/on-boarding-03.png
  public/images/on-boarding-04.png
Labels: enhancement, style

#384 Fix/Mobile-search-page
  Components/Detail/DetailArticle.tsx
  Components/Layouts/GNB.tsx
  Components/Layouts/SearchBar.tsx
  Components/Main/DetailModal.tsx
  Components/Main/MainSection.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/search.tsx
Labels: enhancement

#385 Releases Ver. 1.2.1
  Components/Common/Auth/AuthButton.tsx
  Components/Common/Auth/AuthInput.tsx
  Components/Common/Auth/ErrorMessageBox.tsx
  Components/Common/Auth/HelperTextBox.tsx
  Components/Common/PrimaryButton.tsx
  Components/Common/TopButton.tsx
  Components/CreatePost/Post/Post.tsx
  Components/Detail/DetailArticle.tsx
  Components/Detail/DetailBadgesContainer.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
  Components/Detail/DetailSide/DetailSide.tsx
  Components/Detail/DetailSide/DetailSideProject.tsx
  Components/Detail/DetailTitle.tsx
  Components/Detail/RelatedProject/RelatedProject.tsx
  Components/Layouts/Footer.tsx
  Components/Layouts/GNB.tsx
  Components/Layouts/Notification.tsx
  Components/Layouts/SearchBar.tsx
  Components/Main/Banner.tsx
  Components/Main/DetailModal.tsx
  Components/Main/MainSection.tsx
  Components/Main/index.ts
  Components/Mobile/HambergerMenu.tsx
  Components/Mobile/SelectField.tsx
  Components/MyPage/TabProfile/DropDown.tsx
  Components/MyPage/TabProfile/EditProfileContainer.tsx
  Components/MyPage/TabProfile/ProfileCommentInput.tsx
  Components/MyPage/TabProfile/ShowProfileContainer.tsx
  README.md
  hooks/common/useIntersect.ts
  hooks/common/useIsMobile.ts
  hooks/query/useUserProfile.ts
  lib/recoil/myPageAtoms.ts
  package.json
  pages/_app.tsx
  pages/auth/login.tsx
  pages/auth/signup.tsx
  pages/index.tsx
  pages/m-preparing.tsx
  pages/on-boarding.tsx
  pages/profile/[[...userId]].tsx
  pages/search.tsx
  public/icons/Mobile/hamberger_menu.svg
  public/icons/back-arrow.svg
  public/icons/top-button.svg
  public/images/anonImage.png
  public/images/anonImage.webp
  public/images/main-banner.png
  public/images/on-boarding-01.png
  public/images/on-boarding-02.png
  public/images/on-boarding-03.png
  public/images/on-boarding-04.png
  public/images/thumnail_default.webp
  types.d.ts
  utils/card/findThumbnailInContent.ts
  utils/commons/checkUrl.ts
Labels: version

#387 Feat/next font
  pages/_app.tsx
  pages/_document.tsx
Labels: enhancement

#386 Style/detail styled - 디테일페이지 반응형
  Components/Detail/Comment/Comment.tsx
  Components/Detail/Comment/CommentInput.tsx
  Components/Detail/Comment/CommentItem.tsx
  Components/Detail/DetailArticle.tsx
  Components/Detail/DetailBadges.tsx
  Components/Detail/DetailBadgesContainer.tsx
  Components/Detail/DetailContent.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
  Components/Detail/DetailHeader/ShowMoreModal.tsx
  Components/Detail/DetailTitle.tsx
  Components/Detail/RelatedProject/RelatedProject.tsx
  Components/Main/MainSection.tsx
Labels: style

#389 fix(Main): Main Layout을 급히 수정합니다.
  Components/Common/TopButton.tsx
  Components/Detail/DetailArticle.tsx
  Components/Layouts/EmptyContent.tsx
  Components/Main/MainSection.tsx
Labels: hotfix

#390 fix: 메인 배너가 생기며 드롭다운 위치 버그 픽스
  Components/Main/MainSection.tsx
  pages/_app.tsx
  pages/_document.tsx
Labels: hotfix

#391 fix: png to webp
  Components/Main/Banner.tsx
  public/images/main-banner.png
  public/images/main-banner.webp
Labels: enhancement

#392 Docs/readme.md
  README.md
  package.json
  public/favicon.ico
  public/icons/favicon.ico
  public/images/favicon.ico
  public/logos/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  supabase/.gitignore
  supabase/config.toml
  supabase/seed.sql
Labels: documentation

#393 Releases Ver. 1.2.2
  Components/Common/TopButton.tsx
  Components/Detail/Comment/Comment.tsx
  Components/Detail/Comment/CommentInput.tsx
  Components/Detail/Comment/CommentItem.tsx
  Components/Detail/DetailArticle.tsx
  Components/Detail/DetailBadges.tsx
  Components/Detail/DetailBadgesContainer.tsx
  Components/Detail/DetailContent.tsx
  Components/Detail/DetailHeader/DetailHeader.tsx
  Components/Detail/DetailHeader/ShowMoreModal.tsx
  Components/Detail/DetailTitle.tsx
  Components/Detail/RelatedProject/RelatedProject.tsx
  Components/Layouts/EmptyContent.tsx
  Components/Main/Banner.tsx
  Components/Main/MainSection.tsx
  README.md
  package.json
  pages/_app.tsx
  pages/_document.tsx
  public/favicon.ico
  public/icons/favicon.ico
  public/images/favicon.ico
  public/images/main-banner.png
  public/images/main-banner.webp
  public/logos/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  supabase/.gitignore
  supabase/config.toml
  supabase/seed.sql
Labels: version
